:fire: Remove local `ApiGen` dependecy.
Run as global when v5.0.0 released.

diff --git a/script/deploy/documentation b/script/deploy/documentation
--- a/script/deploy/documentation
+++ b/script/deploy/documentation
@@ -6,7 +6,17 @@ NML_VERSION=$(git describe)
 # Generate Api in: output/api
 script/build-api
 
+if [[ $? -ne 0 ]]; then
+    echo 'Error! Unable to build documentation!'
+    exit 1
+fi
+
 git checkout gh-pages
+
+if [[ $? -ne 0 ]]; then
+    echo 'Error! Unable to checkout branch!'
+    exit 2
+fi
 
 # Clean current (old) api directory
 rm -rf api
